default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vaicar-image-uploader_development
test:
  <<: *default
  database: vaicar-image-uploader_test
production:
  <<: *default
  database: vaicar-image-uploader_production
  username: postgres
  password: <%= ENV['VAICAR-IMAGE-UPLOADER_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
